version: '3.1'

services:
  dev:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm start

  prod:
    build:
      context: .
    ports:
      - 3000:3000
    command: npx serve -p 3000 -s build
