version: '3.1'

services:
  dev:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      REACT_APP_CAMPAIGN_PRIORITY: 1,2,3,4,5,6,7,8,9,10

prod:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      REACT_APP_CAMPAIGN_PRIORITY: 1,2,3,4,5,6,7,8,9,10
    command: npx serve -p 3000 -s build
