version: '3.1'

services:
  web:
    build: 
      context: .
    ports:
      - 80:3000
    volumes:
      - .:/app
    environment:
      CAMPAIGN_PRIORITY: 1,2,3,4,5,6,7,8,9,10
    command: npm start
